### ISSUE TITLE
Quick Reference for controller scope is missing

### ISSUE THREAD

**Issue by delight** [grails/grails-doc#107]
As noted @ http://grails.org/doc/latest/guide/single.html#controllersAndScopes since grails 2 its possible to specify the scope of a controller by e.g.:

static scope = "singleton"

There is no entry yet in the "Quick Reference"

**Comment by guramritpal-jft** [comment]
http://grails.github.io/grails-doc/latest/guide/single.html#controllersAndScopes

@delight 
this issue has been solved please close this issue.   { teamjft 
}

**Comment by anshbansal** [comment]
@guramritpal-jft It is not necessary for the authors to close. Sometimes they are not available so just comment that this should be closed. @graemerocher or @jeffbrown can close this also.

**Comment by jeffbrown** [comment]
I think this was fixed with https://github.com/grails/grails-doc/commit/4c157028648addea2a692319e6cc2a65307e5fdd

**Comment by guramritpal-jft** [comment]
@anshbansal  Thanks for information.i will keep in mind next time.
