### ISSUE TITLE
eference to the XmlHttpRequest object with dojo is 'response', not 'e'

### ISSUE THREAD

**Issue by valdomir** [grails/grails-doc#132]
At this section http://grails.org/doc/latest/guide/theWebLayer.html#ajaxEvents

says that 

"a reference to the XmlHttpRequest object you can use the implicit event parameter e to obtain it:

<g:javascript>
    function fireMe(e) {
        alert("XmlHttpRequest = " + e)
    }
}
</g:javascript>
<g:remoteLink action="example"
              update="success"
              onSuccess="fireMe(e)">Ajax Link</g:remoteLink>

"

but the name 'e' for implicit parameter is only valid if you use Jquery; if you use Dojo, you shoud use 'response':

<g:remoteLink action="example"
              update="success"
              onSuccess="fireMe(response)">Ajax Link</g:remoteLink>

Thanks,

**Comment by guramritpal-jft** [comment]
@jeffbrown  anybody knows about status of this issue.it was opened long time ago..

**Comment by ManvendraSK** [comment]
@jeffbrown This issue is not longer pertain to current release of docs. It can be safely closed.
