### ISSUE TITLE
iText version

### ISSUE THREAD

**Issue by chery-qualset-hcd-ca-gov** [grails/grails-doc#237]
Can we please upgrade the iText version?  This causes so many conflicts with plugins that use newer versions.

**Comment by jeffbrown** [comment]
I think this is an issue for grails-core, not grails-doc.

**Comment by chery-qualset-hcd-ca-gov** [comment]
It is definitely pulled in by grails-doc.  https://github.com/grails/grails-doc/tree/master/lib

**Comment by jeffbrown** [comment]
Does that version affect plugins or is it the one coming from grails-core that is problematic?

**Comment by jeffbrown** [comment]
I would think the one at https://github.com/grails/grails-core/blob/4be8d709ebc57136ee028cba358c598d5c552501/grails-docs/build.gradle#L19 would be the culprit.

**Comment by jeffbrown** [comment]
The grails-doc project is where we author our user guide.  I don't think the jar you linked above would have any impact on any project other than this one.
