### ISSUE TITLE
Grails 3.0.1 single pdf documentation is cutten

### ISSUE THREAD

**Issue by rozpuszczalny** [grails/grails-doc#250]
There is a issue in single.pdf file, right margin cuts some of text and it cannot be read well. 
![zrzut ekranu 2015-05-07 o 23 43 41](https://cloud.githubusercontent.com/assets/7627635/7526564/ef8d572e-f512-11e4-9302-f7749aa3ed9d.png)

**Comment by bemace** [comment]
This is embarrassing, and gives a bad impression to people who are using or evaluating the framework. If you're not going to make it work correctly, at least remove the link.

**Comment by woodmawa** [comment]
still showing problem in grails 3.0.2 pdf - is this fixed or not?

**Comment by proshin-roman** [comment]
The problem is still there - PDF file is not readable due to a cutted right side. I was able to fix it "at run-time" by fixing a width of div#main to 980px - after that a web page can be printed to a PDF file.
