### ISSUE TITLE
g:pageProperty is very poorly documented

### ISSUE THREAD

**Issue by syntheticzero** [grails/grails-doc#252]
The documentation for pageProperty in every version of the Grails documentation is laughably incomplete. It's not made clear at all what the options are, how the name of the pageProperty relates to content on the original page, etc.

I suggest people write more formal documentation and/or include many more examples than the single cryptic example that only refers to how a page property might refer to a body onload property. In particular, the "content tag" example from here would be extremely helpful:

This comment on StackOverflow helped me a great deal, for example:

http://stackoverflow.com/questions/339424/are-there-any-good-tutorials-for-using-sitemesh-in-a-grails-application

"the g:pageProperty is a very powerful, but very poorly documented thing. Lets say in my layout I specify where to put some content like this:

```
<html>
<body>
<g:pageProperty name="page.header" />
</body>
```

Now in my page I can specify some content:

```
<content tag="header">
<!-- header -->
</content>
```

Sitemesh will take the content tag, regardless of actual position in the HTML of the page and place it where it needs to go in the flow of the layout.

Even better, if within my page I render a template that also specifies a content area with a tag of "header", it will overwrite the first declaration, and it will be the template's content that will be rendered in the final layout."

**Comment by graemerocher** [comment]
Feel free to improve it, the docs are open source and here https://github.com/grails/grails-doc/blob/master/src/en/ref/Tags/pageProperty.gdoc

**Comment by anshbansal** [comment]
This should be closed now.
