### ISSUE TITLE
create-tag-lib vs. create-taglib

### ISSUE THREAD

**Issue by asoftwareguy** [grails/grails-doc#254]
In the documentation, the command is referred to as 'create-tag-lib'. On the command line, what actually works is 'create-taglib'. Which is correct? I can update the docs or the code as needed. This is as of Grails 3.0.1

**Comment by jeffbrown** [comment]
The command is defined at https://github.com/grails/grails-profile-repository/blob/master/profiles/web/commands/create-taglib.yml.

Maybe we should create a synonym, similar to what is done at https://github.com/grails/grails-profile-repository/blob/bc80665ea5b383533346dc10c8d7ec6419da4200/profiles/base/commands/run-app.groovy#L3.

**Comment by asoftwareguy** [comment]
@jeffbrown sure, we can do that as well. I couldn't remember what the command used to be in pre-3.0 versions, so I checked, and it is 'create-tag-lib'. I think a synonym is a good idea (definitely easier than updating all of the doc references).

**Comment by asoftwareguy** [comment]
@jeffbrown @graemerocher is there a way to define synonyms in the YAML syntax, or does it have to be converted to Groovy config?

**Comment by Dhanendra-jft** [comment]
@asoftwareguy @jeffbrown Has this been resolved? For this i check the documentation and also tested the app config. In version 3.0.x we use create-taglib to create a tag lib. Any thing else on this?

**Comment by asoftwareguy** [comment]
See above. There was a PR in the grails-profile-repository to create an alias.
