### ISSUE TITLE
Grails 3 datasource documentation inconsistency

### ISSUE THREAD

**Issue by Fitzoh** [grails/grails-doc#257]
from http://grails.github.io/grails-doc/3.0.x/guide/upgrading.html

>Some files that were previously created by Grails 2.x are no longer created. These have either been removed or an appropriate replacement added. The following table lists files no longer in use:

>grails-app/conf/DataSource.groovy	Merged together into **application.yml**

and

>The configuration of the application will need to be migrated, this can normally be done by simply renaming grails-app/conf/Config.groovy to grails-app/conf/application.groovy and merging the content of grails-app/conf/DataSource.groovy into grails-app/conf/**application.groovy**.

Should it be application.groovy, or application.yaml (if either one works, that should probably be explicit)

Later on, http://grails.github.io/grails-doc/3.0.x/guide/conf.html#dataSource states

>Once you have the JAR resolved you need to get familiar Grails' DataSource descriptor file located at grails-app/conf/**DataSource.groovy**. This file contains the dataSource definition which includes the following settings: 

And now we're back to DataSource.groovy (and using groovy config in the examples).

**Comment by graemerocher** [comment]
the last one is an error and needs fixing, the second one is true you can use `application.groovy` or `application.yml`

**Comment by anshbansal** [comment]
Shouldn't this be closed now?
