### ISSUE TITLE
Grails 2.5 documentation missing what's new

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#261]
Hi

The documentation for Grails 2.5 is missing what is new in 2.5 in the Introduction section.

http://grails.github.io/grails-doc/2.5.0/guide/introduction.html

**Comment by anshbansal** [comment]
@graemerocher 
I am ok sending the PR for the issues that I am opening but I need some clarity. Others need opinions. Like whether this is worth it or not supported etc.

**Comment by anshbansal** [comment]
@graemerocher Do you think this will be possible? This isn't something that I can help with. If taking care is tough I'll just close it so 3.x docs can be taken care of instead.

**Comment by jameskleeh** [comment]
Closing because of 2.x
