### ISSUE TITLE
Content for GORM documentation

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#266]
Hi

I was reading through grails 2.4 documentation when I found that the documentation has some details in the introduction section under the heading "More Advanced Subqueries in GORM" at the link
 http://grails.github.io/grails-doc/2.5.0/guide/introduction.html#whatsNew24  But this information is not present in the main GORM docuementation.  The complete section "More Advanced Subqueries in GORM" can be merged into main GORM documentation. 

This is required because in Grails 3 docs "What's new in Grails 2.4" is not present. So essentially this information has been lost in grails 3 docs.

**Comment by guramritpal-jft** [comment]
@anshbansal  you are right .
@jeffbrown  if it fine i will be happy to add this information to gorm documentation.. please comment.

**Comment by anshbansal** [comment]
@guramritpal-jft This is open source. I don't think you need to discuss every time. If you are interested go ahead. This is a doc change not code change. It is good to start a discussion before a code change.

**Comment by jeffbrown** [comment]
@anshbansal Any time someone is unsure they ask.  I think that works fine.

**Comment by guramritpal-jft** [comment]
@anshbansal  @jeffbrown  i have added the missing content as per https://github.com/grails/grails-doc/issues/266 this issue . please check let me know correction.

**Comment by guramritpal-jft** [comment]
@anshbansal close this issue [solved].
