### ISSUE TITLE
Broken links for Standalone GORM and GSP

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#267]
In grails 2.5.0 docs http://grails.github.io/grails-doc/2.5.0/guide/introduction.html the links to spring.io are broken. 
https://spring.io/guides/gs/accessing-data-gorm/
https://spring.io/guides/gs/accessing-data-gorm-mongodb/

Moreover this information is completely missing in Grails 3 documentation.

**Comment by anshbansal** [comment]
Any idea where this information may be now?

**Comment by graemerocher** [comment]
The articles were hosted by Pivotal, since Grails is no longer part of Pivotal they have been deprecated and removed from the spring.io site: https://github.com/spring-guides/deprecate-gs-accessing-data-gorm-mongodb and https://github.com/spring-guides/deprecate-gs-accessing-data-gorm
