### ISSUE TITLE
Grails 3 docs inconsistency regarding web app folder

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#271]
Upgrading from Grails 2.x says that 
> web-app is now src/main/webapp.

Then it says that 
> For public assets such as static HTML pages and so on these should go in src/main/resources/public.

So which is it?

**Comment by graemerocher** [comment]
`src/main/resources/public` is recommended as `src/main/webapp` only gets included in WAR packaging but not in JAR packaging

**Comment by anshbansal** [comment]
Ok. Will send a PR for correcting that.

**Comment by anshbansal** [comment]
@graemerocher Are the new documentation released with new versions? I mean if I want to see the documentation with the current SNAPSHOT of this repo when will I be able to see that?

**Comment by graemerocher** [comment]
@anshbansal Snapshots are published to http://grails.github.io/grails-doc/snapshot/

**Comment by anshbansal** [comment]
@graemerocher But they are of 3.0.0 and do not contain the changes.

**Comment by graemerocher** [comment]
Ah yeah, I remember now, we stopped publishing snapshots via github because it means that each change resulted in the size of the Git repo growing by 10mb since Git maintains the history. I'm not sure if there is a way around that unless we force push the repo to flatten the history somehow

**Comment by anshbansal** [comment]
The README has this URL also
http://hudson.grails.org/job/grails_docs_2.0.x/lastSuccessfulBuild/artifact/build/docs/

Maybe that can be used? But that URL is not opening.

**Comment by graemerocher** [comment]
That is our old Hudson server which will soon be shutdown.

**Comment by anshbansal** [comment]
I'll just take a checkout and do that on local. 

BTW pushing the snapshot build into a separate repository might work. On daily basis perhaps. Send a hard reset for the history by 1 level to the repo before pushing new one. Hard reset on server is not a good idea in general but in this case could be used to control the repo's size without side effects. That way snapshots should be available. Maybe one day old but still available.

**Comment by graemerocher** [comment]
Yeah probably not a bad idea. we'll see what we can do, I don't want to hard reset / force push this main repo as it could have side effects so the secondary repo solutions is definitely an option
