### ISSUE TITLE
Lack of clarity for logging in 3.0.2 documentaiton

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#274]
While trying a Grails 3.0.2 app I hit this issue - how to inject log in grails 3? Earlier I was using @Log4j for this. But now I was not sure. 

I looked and found some issues.
* https://grails.github.io/grails-doc/latest/ref/Plug-ins/logging.html says that Log4j is supported by this. Is that true? Shouldn't this be changed to logback?
* How to inject logger in various places? There is no example. https://grails.github.io/grails-doc/latest/guide/single.html#loggingsays to look in logback documentation for configuration. But there is no example for how to inject the correct logger in Grails.

**Comment by anshbansal** [comment]
Closed it by mistake.

**Comment by anshbansal** [comment]
bump. If anyone can share some info I would be willing to update the docs.

**Comment by graemerocher** [comment]
@anshbansal First bullet should refer to logback yes. Bullet 2, I'm not sure what you mean by "inject the correct logger".. .all artefacts have a `log` property by default, alternatively you can just use the Groovy logging annotations

**Comment by anshbansal** [comment]
@graemerocher I meant how to get the logback logger to be injected. The default one present is logback? For including in util classes using groovy annotations? The ones that I am aware of are @Log4j. Is there anything else?

**Comment by guramritpal-jft** [comment]
as @graemerocher  said its rigth.

all artefacts have a log property by default.
