### ISSUE TITLE
fieldError is undocumented and incorrectly documented in code

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#281]
I was going through the code in ValidationTagLib. I noticed that fieldError is not documented in grails online docs. Also it seems to be incorrectly documented in the code's javadocs.

Is that an internal thing?

**Comment by anshbansal** [comment]
It was Grails 3.0.2 code that I was going through.

**Comment by anshbansal** [comment]
bump.

**Comment by guramritpal-jft** [comment]
Renders an error message for the given bean and field.
eg. <g:fieldError bean="${book}" field="title" />

@anshbansal  
This issue has been fixed just check and comment if im wrong....!

**Comment by jeffbrown** [comment]
@anshbansal 

> Is that an internal thing?

No.

> I noticed that fieldError is not documented in grails online docs.

Would you like to send a pull request to add it to https://github.com/grails/grails-doc/tree/master/src/en/ref/Tags ?

**Comment by guramritpal-jft** [comment]
@jeffbrown 
can i try...? just let me know..

**Comment by jeffbrown** [comment]
@guramritpal-jft Of course.  Thanks!

**Comment by guramritpal-jft** [comment]
@jeffbrown  how to do it just brief...thanks im not able to find file in pull request

**Comment by jeffbrown** [comment]
@guramritpal-jft You aren't able to find the file because it doesn't exist.  See the others at https://github.com/grails/grails-doc/tree/master/src/en/ref/Tags for lots of examples.  You could send a pull request which adds `fieldError.gdoc` to that directory.

**Comment by anshbansal** [comment]
@guramritpal-jft Look at grails doc about how grails doc are generated. There is a section called Project Documentation

**Comment by anshbansal** [comment]
Just adding that the PR above does not take care of my suspicion that it is incorrectly documented in the code. The above PR has added to grails docs but it is copied from the code. Now it may be incorrect in both places.

**Comment by jeffbrown** [comment]
@anshbansal Feel free to correct.

**Comment by anshbansal** [comment]
@jeffbrown I'll look at the code and try to correct. Just added the comment so that there is no confusion about why the PR is not enough to close this.

**Comment by jeffbrown** [comment]
It isn't closed and I wouldn't intentionally close it until it was all addressed.

**Comment by guramritpal-jft** [comment]
@anshbansal  Sure feel free to correct.

**Comment by anshbansal** [comment]
@guramritpal-jft If you are interested then you can take a look at the code of ValidationTagLib https://github.com/grails/grails-core/blob/master/grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/ValidationTagLib.groovy

I was going through it when I noticed that the tag fieldError has 5 properties in the source's javadoc.  But in the implementation only two of them are ever used. The attrs was not passed to the called function either. I think it would be good to do a PR for the code. 

e.g.
The javadoc says that the tag has a property encodeAs but the code just says encodeAs: "HTML". Similarly need to add the functionality for all three optional parameters. They are not considered in the code.

**Comment by guramritpal-jft** [comment]
@anshbansal     encodeAs:codec field is used in renderErrors tag check  
where as in case of   tag fieldError  encodeAs: "HTML" only hardcoded String. 
either  need to correct both java docs and grails docs or need to add functionality. 

"tag fieldError has 5 properties in the source's javadoc. But in the implementation only two of them are ever used". statement Correct. 
I would like to Correct at both levels code level and doc level. please comment.
                                                                                                                        Thanks

**Comment by guramritpal-jft** [comment]
@anshbansal  waiting......

**Comment by anshbansal** [comment]
@guramritpal-jft I am not sure what clarification is required from me. Can you please explain?

**Comment by guramritpal-jft** [comment]
@anshbansal  read my last comment....! There is no implementation for the last 3 attributes .so we have 2 choices. Either remove those attribute declaration from doc and source code file or add implementation to those attributes

**Comment by guramritpal-jft** [comment]
@jeffbrown  can u look at this linkhttps://github.com/grails/grails-core/blob/master/grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/ValidationTagLib.groovy
There is no implementation for the last 3 attributes.  Either remove those attribute declaration from doc and source code file or add implementation to those attributes.

**Comment by guramritpal-jft** [comment]
@graemerocher  can u look at this link 
https://github.com/grails/grails-core/blob/master/grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/ValidationTagLib.groovy
There is no implementation for the last 3 attributes. Either remove those attribute declaration from doc and source code file or add implementation to those attributes.

**Comment by jameskleeh** [comment]
Removed the attributes from the docs that aren't used in the source
