### ISSUE TITLE
Seems that part of Content Negotiation docs is wrong

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#284]
The docs say that
>The result of this on the server side is a format property on the response object with the value xml.

But it seems to be wrong. Shouldn't it be `request params object` instead of `response object`?

**Comment by graemerocher** [comment]
No, there is a 'format' property which exists on the response https://github.com/grails/grails-core/blob/master/grails-plugin-mimetypes/src/main/groovy/org/grails/web/mime/HttpServletResponseExtension.groovy#L94
