### ISSUE TITLE
Improvement | Make snapshot documentation available

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#288]
Currently snapshot documentation is not available as discussed in https://github.com/grails/grails-doc/issues/271.  It would be nice to have that available.

@graemerocher  Putting this issue so that it doesn't slip out of mind.

**Comment by anshbansal** [comment]
@graemerocher Let me know if I can help in getting the snapshots up.

**Comment by sdelamo** [comment]
We used to publish snapshot of the docs but it caused the github repo to become huge since the diffs of the groovy docs were big. That it is the reason why we stop doing it.
