### ISSUE TITLE
Seems that part of building docs is broken

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#289]
While editing docs I noticed that a lot of pages have "Source" at their bottom in the gdoc files. But the actual docs do not have anything other than the Source at their bottom.

e.g. The below has a heading Source but nothing is present there. What is this supposed to be?
https://grails.github.io/grails-doc/latest/ref/Tags/actionSubmit.html

**Comment by graemerocher** [comment]
It used to be that it would show the source code of the tag, but it seems this feature no longer works

**Comment by anshbansal** [comment]
You can the code was inserted into the documentation or a link was created?

**Comment by graemerocher** [comment]
The code was inserted

**Comment by anshbansal** [comment]
Closing as raised issue in core
