### ISSUE TITLE
Where should the bug report's archives be uploaded for Grails 3?

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#294]
It currently says that it is for archives to grials-JIRA. But that is not correct anymore so what should this be changed to?

**Comment by jeffbrown** [comment]
> It currently says that it is for archives to grials-JIRA.

What is the "it" that you are referring to?

**Comment by anshbansal** [comment]
@jeffbrown "it" refers to the package created by the bug-report command.

**Comment by graemerocher** [comment]
They should be uploaded to a github repository, since Github issues doesn't support attachments

**Comment by anshbansal** [comment]
I think the command is not needed anymore seeing that repositories are needed now for reproducing the problem. Started a thread on google groups to discuss this.
https://groups.google.com/forum/#!topic/grails-dev-discuss/ULVxlltFojg
