### ISSUE TITLE
Should gradle commands for grails be part of grails documentation?

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#295]
I was looking at https://github.com/grails/grails-doc/blob/master/src/en/ref/Command%20Line/clean.gdoc when it came to my mind that should I be sending pull request for gradle commands? Like clean can be used be like `grails clean` or `gradle clean`. 

This information can be added to "Contributing Documentation" part.

**Comment by graemerocher** [comment]
It may want to be mentioned that `grails clean` delegates to `gradle clean`, but I don't think we need docs for every Gradle command
