### ISSUE TITLE
Testing type and phase chapter outdated

### ISSUE THREAD

**Issue by dovydasvenckus** [grails/grails-doc#305]
Grails 3 uses 

    grails test-app -unit 

syntax instead of

    grails test app unit:

And using phase:type syntax seems to have some differences

    grails test-app --clean -unit:spock

This command end up running integration tests.

**Comment by anshbansal** [comment]
@dovydasvenckus You could send a Pull request. But always add references in case someone else wants to send PR.
Adding reference for the information https://github.com/grails/grails-core/issues/9082.

**Comment by anshbansal** [comment]
There seems to be no phase:type syntax anymore. I looked at the source and there seems to be no such handling.
https://github.com/grails/grails-profile-repository/blob/master/profiles/base/commands/test-app.groovy

**Comment by graemerocher** [comment]
@anshbansal Yes since phases and type make no sense in the context of Gradle they were removed

**Comment by dovydasvenckus** [comment]
Thanks for information. I could try to fix documentation. But English is not my primary language. My writing skills are poor, because I rarely write in English.
