### ISSUE TITLE
Seems that docs regarding quit and exit are misleading

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#307]
The docs says that exit is for interactive mode while quit is for the forked mode. Is this correct?

I was going through https://github.com/grails/grails-core/blob/master/grails-shell/src/main/groovy/org/grails/cli/GrailsCli.groovy when I noticed that both of these commands are doing the same thing at least for the interactive mode.

**Comment by jeffbrown** [comment]
`quit` is supposed to stop the forked application before exiting interactive mode.  If that isn't happening then that would be a bug in core.

**Comment by jeffbrown** [comment]
> The docs says that exit is for interactive mode while quit is for the forked mode.

I think they are both for interactive mode.  Are there comments in the docs that suggest otherwise?

**Comment by anshbansal** [comment]
5.1 Interactive Mode
If you want to exit interactive mode and stop an application that is running in forked mode, use the quit command.

**Comment by sdelamo** [comment]
This is the exact quote as of 3.3.1

> To exit interactive mode enter the exit command. Note that if the Grails application has been run with run-app normally it will terminate when the interactive mode console exits because the JVM will be terminated. An exception to this would be if the application were running in forked mode which means the application is running in a different JVM. In that case the application will be left running after the interactive mode console terminates. If you want to exit interactive mode and stop an application that is running in forked mode, use the quit command. The quit command will stop the running application and then close interactive mode.
