### ISSUE TITLE
Regarding public fork of grails mentioned in the docs

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#310]
I was reading the docs on contributing and saw this

"Contributing to the documentation is simpler for the core framework because there is a public fork of the http://github.com/grails/grails-doc project that anyone can request commit access to. So, if you want to submit patches to the documentation, simply request commit access to the following repository http://github.com/pledbrook/grails-doc by sending a GitHub message to 'pledbrook' and then commit your patches just as you would to any other GitHub repository."

What is this supposed to be? I mean anyone can make a public fork so why is this one special?

**Comment by bobbywarner** [comment]
@anshbansal This is legacy.  It was originally meant to be an open fork that anyone could push directly to and Peter Ledbrook would then review and merge into the main doc repo.  The idea was to encourage contributions.  This is no longer the case though and this comment should be removed from the documentation.  The correct thing to do is submit pull requests to `grails/grails-doc`.
