### ISSUE TITLE
Is links.yml needed or redundant?

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#325]
There is a file https://github.com/grails/grails-doc/blob/master/src/en/guide/links.yml. Is this an old file that is not needed anymore? Asking this as I have added a new section which is coming in documentation on building but I never touched this file.

**Comment by graemerocher** [comment]
Yes it is still need to avoid hard coding references to chapters. You can do `[My Link|guide:hibernate]` instead

**Comment by anshbansal** [comment]
And this is part of the docs plugin and can be used even outside this repository? I mean this is not a hack? If yes, this is not documented. Can it be used for arbitrary properties?  Then maybe this https://github.com/grails/grails-core/issues/9097 is not needed

**Comment by graemerocher** [comment]
Yes it is a feature, and no it isn't documented :)

**Comment by anshbansal** [comment]
For arbitrary properties or for only for internal links?

**Comment by graemerocher** [comment]
Only for internal links
