### ISSUE TITLE
local.properties is not read by build script

### ISSUE THREAD

**Issue by rlovtangen** [grails/grails-doc#339]
When building documentation, grails-core source is downloaded, but this can be avoided:

> Additionally you can create a local.properties file with this variable set:
> grails.home=/home/user/projects/grails-core

(https://grails.github.io/grails-doc/3.0.3/guide/contributing.html#patchesDoc)

I can't get this to work. Tried with both absolute and relative path. Can't find any references to local.properties in build.gradle, the only references I find is in .gitignore and 4 .gdoc-files.

Pointing to grails core on the command line works. E.g.

    ./gradlew -Dgrails.home=/home/user/projects/grails-core docs

**Comment by anshbansal** [comment]
I think this should be gradle.properties. What do you think?

**Comment by rlovtangen** [comment]
Tried to put grails.home in gradle.properties, but still fetching grails source.

**Comment by anshbansal** [comment]
I made a PR that fixes this. The build was not reading the project properties.
