### ISSUE TITLE
Update grails version in docs

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#351]
I noticed that for the past two releases the docs grails version has not been updated. So although the release is of 3.0.3 and 3.0.4 the grails version at the top still says 3.0.2

Maybe create a script for releasing the docs?

**Comment by jeffbrown** [comment]
@anshbansal Are you interested in submitting a PR?  I haven't looked at it but 1 possibility is that we might want to discover the version number dynamically using something like what was done at https://github.com/grails/grails3-functional-tests/commit/9f0ca378f5c7c5087ca38149d3fd5136a0820199.

**Comment by ManvendraSK** [comment]
@graemerocher this issue can now be closed.
