### ISSUE TITLE
HibernateCriteriaBuilder

### ISSUE THREAD

**Issue by chery-qualset-hcd-ca-gov** [grails/grails-doc#357]
I was reading https://grails.github.io/grails-doc/latest/ref/Domain%20Classes/createCriteria.html and clicked on the link 'http://grails.github.io/grails-doc/3.0.x/api/grails/orm/HibernateCriteriaBuilder.html' and got a 404.

Is there documentation for api/grails/orm/HibernateCriteriaBuilder?

**Comment by Dhanendra-jft** [comment]
I would like to add on in this issue, I was just going through the docs and found that whole orm folder is missing from the api/grails.

Example - http://grails.github.io/grails-doc/3.0.x/api/grails/orm/PagedResultList.html which is also giving 404 error, page not found, link comes under api/grails/orm. But when you change the grails version i.e 2.0.x which makes a link http://grails.github.io/grails-doc/2.0.x/api/grails/orm/PagedResultList.html which contains the actual docs.

FYI: @jeffbrown

**Comment by guramritpal-jft** [comment]
@chery-qualset-hcd-ca-gov  Please close this issue as it has been solved.  Thanks

**Comment by chery-qualset-hcd-ca-gov** [comment]
So, either we remove the links in the Domain Classes/CreateCriteria gdoc or we point them to the right place. 

The first case is easy.  

In the second case, I don't know how the API documentation gets built and published to determine the right place to point the links.

The source code is found in grails-data-mapping\grails-datastore-gorm-hibernate4\src\main\groovy\grails\orm\HibernateCriteriaBuilder.java
 or 
C:\Users\cqualset\Documents\GitHub\grails-data-mapping\grails-datastore-gorm-hibernate\src\main\groovy\grails\orm\HibernateCriteriaBuilder.java

I can find the groovyDoc for grails.orm.HibernateCriteriaBuilder for v 2.2.x (http://grails.github.io/grails-doc/2.2.x/api/grails/orm/HibernateCriteriaBuilder.html), but not v 2.3 or later.  

The grails.orm package containing HibernateCriteriaBuilder also contains createAlias, rlike and getHibernateDetachedCriteria.

**Comment by graemerocher** [comment]
The links need to be corrected to point to http://grails.github.io/grails-data-mapping/latest/api/index.html

**Comment by graemerocher** [comment]
Thanks
