### ISSUE TITLE
BuildConfig.groovy references

### ISSUE THREAD

**Issue by and-dmitry** [grails/grails-doc#370]
There are a few references to `BuildConfig.groovy` in grails-3 documentation which have to be changed to `build.gradle`. Most of these fixes are not trivial because they require some knowledge of the build system and testing.

**Comment by ManvendraSK** [comment]
**BuildConfig.groovy** instances are already replaced by **build.gradle**. See this commit. Please close this issue.

**Comment by and-dmitry** [comment]
I forgot to check the latest sources before reporting. Sorry.

**Comment by ManvendraSK** [comment]
No Problem @and-dmitry. I appreciate efforts. :-)
