### ISSUE TITLE
Grails 3: XSSPrevention says Application.groovy is Default Generated Config File

### ISSUE THREAD

**Issue by lhigginbotham** [grails/grails-doc#389]
Specifically:
"GSP features the ability to automatically HTML encode GSP expressions, and as of Grails 2.3 this is the default configuration. The default configuration (found in application.groovy) for a newly created Grails application can be seen below:"

This should be listed as application.yml.  Additionally, the code example below should probably be in yml instead of the Groovy format.

I can open a PR if this is something that should be changed.

**Comment by graemerocher** [comment]
PRs welcome

**Comment by dovydasvenckus** [comment]
@graemerocher Is it possible to set this parameter in YML file.

    grails.views.gsp.filteringCodecForContentType.'text/html' = 'html'

**Comment by vonovak** [comment]
this issue can be closed, the docs are already fixed

http://grails.github.io/grails-doc/latest/guide/single.html#xssPrevention
