### ISSUE TITLE
Scrolling of docs is broken in Safari

### ISSUE THREAD

**Issue by jamesdh** [grails/grails-doc#419]
Specifically on https://grails.org/single-page-documentation.html

Using Safari, I'm unable to scroll on the docs page. Some amount of attempting will eventually make the browser default side scroll bar appear, at which point one can grab it and drag it to where they'd like, but it's more/less unusable at this point. 

Chrome/Firefox both appear fine.

**Comment by graemerocher** [comment]
Yeah I have found this as well, not sure yet what the solution is, it seems to be the iframe causing issues

**Comment by graemerocher** [comment]
Seems related https://www.codersclan.net/ticket/553

**Comment by Schlogen** [comment]
I'm seeing this in Chrome on Windows

**Comment by vonovak** [comment]
I believe this was fixed by [#31](https://github.com/grails/grails-static-website/pull/31)

**Comment by graemerocher** [comment]
Thanks
