### ISSUE TITLE
There are 2 scroll bars for grails docs of 3.1.0.RC2

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#420]
Environment - Ubuntu 14.04 
Browser - Version 47.0.2526.111 (64-bit)

On the right side there are 2 scroll bars present. One that just takes the new top nav in and out of focus and the other scroll bar can be used to scroll the whole documentation

**Comment by Schlogen** [comment]
What URL are you using?

**Comment by anshbansal** [comment]
https://grails.org/single-page-documentation.html

**Comment by anshbansal** [comment]
My screen size is 1920 X 611 px if that is relevant
