### ISSUE TITLE
Update 7.2.5 Static Resources to include changes from release notes

### ISSUE THREAD

**Issue by AustinAllman** [grails/grails-doc#432]
Add update to 
https://grails.github.io/grails-doc/3.0.x/guide/theWebLayer.html#resources
to include information on adding static resources from the release notes.

https://github.com/grails/grails-core/releases/tag/v3.0.12

> Location of static resources
> 
> In order to resolve an issue around how POST requests are treated for REST applications on non-existent resources, static resources located in src/main/resources/public are now resolved under the /static/*\* URI by default, instead of the base URI /**. If you wish to restore the previous behaviour add the following configuration:
> 
>   grails.resources.pattern = '/**'

**Comment by jameskleeh** [comment]
Done
