### ISSUE TITLE
GORM call 'NotInList' not working in Grails 3.0.x

### ISSUE THREAD

**Issue by squarepegsys** [grails/grails-doc#452]
`findAllNotInList` doesn't seem be to working in Grails 3.0. I tried in 3.0.10 and 3.0.16.

Here is my sample app:
https://github.com/squarepegsys/grails3-notInList

**Comment by graemerocher** [comment]
`NotInList` has never been a supported expression. The list of supported expressions are defined here http://grails.github.io/grails-doc/latest/guide/GORM.html#finders

This is an IDE bug that makes people think it is one

**Comment by squarepegsys** [comment]
That is really interesting since it works fine in Grails 2.5:
https://github.com/squarepegsys/grails2-notInList

But you are right -- even the Grails 2.5 docs show NotInList as working, but the IDE autocompletes it and it does indeed work.
(I found this when upgrading a working Grails 2 app to Grails 3)

**Comment by snimavat** [comment]
I encountered the same issue, when upgrading to grails 3.
It actually worked in grails 2.5.5, but does not work in grails 3
