### ISSUE TITLE
Testing documentation for controllers in 2.5.x wrong?

### ISSUE THREAD

**Issue by cmdcolin** [grails/grails-doc#476]
I was attempting to reproduce the SimpleController and SimpleControllerSpec test here http://docs.grails.org/2.5.5/guide/single.html#unitTestingControllers using grails 2.5.5

For me it seems, the SimpleController test did not pass in grails 2.5.5

If I change the test to expect `controller.response.text == 'hello'` then the test passes

There is a similar thing for the other scenarios in the unitTestingControllers docs like this, for example with passing params. I found that I have to use controller.params.myparam = "test"

If I used grails 3.1 then it does appear to pass the test, but I am wondering if the 2.5.x branch could be fixed? that is, assuming I'm not just missing something on the 2.5 side of things

Also in grails 2.5 the autogenerated tests extend IntegrationSpec while 3.1 extend Specification, so maybe that can be adjusted

I could create a PR if interested

**Comment by jameskleeh** [comment]
Closing because of 2.x

**Comment by cmdcolin** [comment]
2.x issues will not be addressed essentially? Doesn't really affect me anymore, moved on from project but just curious...

**Comment by jameskleeh** [comment]
Correct. We are no longer maintaining 2.x
