### ISSUE TITLE
Grails meta.html docs for 3.1 and 3.2 needs updating

### ISSUE THREAD

**Issue by jknudsen** [grails/grails-doc#482]
The variable names have change to info.app.version and info.app.grailsVersion and are correct on the 3.0.17 documentation.  Could you at least copy the 3.0.17 meta.html to the 3.1 and 3.2 lines? Also from my limited understanding the Description should say that the info.app.version is set by the version property in the build.gradle file and the info.app.grailsVersion is set by the grailsVersion property in the gradle.properties file.

**Comment by jknudsen** [comment]
I created a pull request so this issue can be closed.

**Comment by jknudsen** [comment]
Should I leave it open until the pull request is completed?

**Comment by graemerocher** [comment]
Thanks
