### ISSUE TITLE
Grails 3.2.1: Building a war for Tomcat

### ISSUE THREAD

**Issue by itpragmatik** [grails/grails-doc#520]
1. I added this line to my build.gradle: provided "org.springframework.boot:spring-boot-starter-tomcat"
2. Then I ran grails war
3. Then I copied myapp-0.1.war to $tomcat_home/webapps/ 
4. After I started the tomcat, I don't see any web.xml in $tomcat_home/webapps/myapp/WEB-INF/ directory. The absence of it is preventing me accessing this app from browser as http://localhost:8080/myapp/

What am I missing or doing wrong?

**Comment by itpragmatik** [comment]
Maybe I need to report this into grails github issues as well. Not sure if documentation needs to improve or if there is a bug in grails 3.2.1

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
