### ISSUE TITLE
bad link on Constraints Page of the latest documentation.

### ISSUE THREAD

**Issue by joshk6** [grails/grails-doc#528]
The link 

> Refer to the user guide topic on [Constraints](url) for more information.

doesn't work.  Thanks.

**Comment by jameskleeh** [comment]
Fixed. Thanks for the report

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:42101 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWo5o-003oWq-S6
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:44:16 -0600
Date: Wed, 25 Jan 2017 12:34:57 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485376497;
	bh=wjbT54EPwNQ9zDFrZce3djDdRuApIPvmSqtrYkEgGRM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qlbg2j35RMdulhngL0oXmbBPp+LqoCWOND7modi27P2ME5tuJFHJV4Cvo+YxF0vly
	 FhZCMwgUfS5KIWwy1m4BSlSfG7j7qgiu3OKdm3ZMNEDQu4cqpXW3bg95gAhaygQ3dl
	 n2tdJt6A0KfWUy3WyoaE6/Pb+e1j4eN8oWBwXnLE=
