### ISSUE TITLE
Missing reference in chapter 19

### ISSUE THREAD

**Issue by kastork** [grails/grails-doc#551]
In 19.2, The Underpinnings of Grails, it says,

> Configured Spring Beans
> 
> Most of Grails' configuration happens at runtime. Each plugin may configure Spring beans that are registered in the ApplicationContext. For a reference as to which beans are configured, refer to  the reference guide which describes each of the Grails plugins and which beans they configure.

The "Reference Guide" is not a link.    Googling for "Grails Reference Guide" finds a probable hit for this at [https://www.grails.org/Reference](https://www.grails.org/Reference).  However, upon arriving at that link you are prompted for credentials.

If this resource is going to be referred to in public documentation, it should be (a) linked and (b) viewable without authentication.

I'd file a PR for this, but I think doing it properly will require insider access and knowledge that I don't have.

**Comment by sdelamo** [comment]
"Reference Guide" refers to the right-hand-side navigation:

![the_grails_framework_3_3_0](https://user-images.githubusercontent.com/864788/32290439-5ab8e42a-bf3a-11e7-9e5b-e5fa33d42d5c.png)

**Comment by kastork** [comment]
Okay,

But what you see when you click that link is this:

![image](https://user-images.githubusercontent.com/202288/32290721-297ae882-bef8-11e7-9e6a-9c4449399d1b.png)

**Comment by sdelamo** [comment]
I think that the link https://www.grails.org/Reference does not longer appear in the latest docs. Please, correct me if I am wrong about it.

**Comment by kastork** [comment]
You're right "refer to the reference guide" no longer appears there.
