### ISSUE TITLE
List of Known Deployment Issues Link

### ISSUE THREAD

**Issue by busches** [grails/grails-doc#562]
In section 2.11 Supported Java EE Containers there is the following text:
`Some containers have bugs however, which in most cases can be worked around. A list of known deployment issues can be found on the Grails wiki.` With `list of known deployment issues` linking to the following url: `http://grails.org/Deployment`. This link requires you to login and then gives you `Unauthorized` once you do. 

Where can that link be found at? A Google search returned nothing. If you let me know where it should point to and I can submit a PR.

Thanks.

**Comment by genuinefafa** [comment]
What about [this](https://grails.org/wiki/version/Deployment/92)  but I cannot make it work as "latest" version only.
