### ISSUE TITLE
Cascade page seems to be missing "cascade none" which is arguably the most important type for performance-critical apps.

### ISSUE THREAD

**Issue by jeff1089** [grails/grails-doc#580]
Hibernate seems to reference cascade none as a type based on, for example, this page:

http://pwinckles.blogspot.com/2011/12/how-to-disable-hibernate-cascading.html

Based on current documentation, the most common performance improvement for grails is to, for example, replace:

Class City {}
Class Person { 
   City homeTown
}

with:
Class City {}
Class Person {
  //Don't cascade save the whole dang city!
  Long cityId
}

If the grails team enhanced their documentation to make this use case more user friendly for performance critical applications it would be a significant improvement to the documented behavior of the language.

**Comment by graemerocher** [comment]
http://docs.grails.org/latest/ref/Database%20Mapping/cascade.html

Contributions welcome

**Comment by niravassar** [comment]
I took a look at this and the documentation has a good example of how to not apply cascading.  The example is here: http://docs.grails.org/latest/ref/Database%20Mapping/cascade.html

and references

```


If the association doesn’t define an owner (a "belongs to" relationship):

class Book {
}

class Author {
    static hasMany = [books: Book]
}

then GORM uses a cascading policy of "save-update" by default. So if an Author is deleted the Book associated domains won’t be deleted.
```

For the example of offered below, it is not dealing with objects anymore, just the fk. Essentially, it is bypassing the cascade feature. Thus, i dont think it should be official documentation. 

```
Class City {}
Class Person {
//Don't cascade save the whole dang city!
Long cityId
}
```
