### ISSUE TITLE
4.1.3 Logging - make it clear that grails-logging plugin required for auto log-injection

### ISSUE THREAD

**Issue by amcclain** [grails/grails-doc#598]
http://docs.grails.org/3.3.x/guide/conf.html#logging

Without the grails-logging plugin, Grails artifacts do not get a log property auto-injected as the docs state. Instead, you would need to annotate your classes manually with the `@Slf4j` annotation.

For users who might be upgrading apps and not starting from a blank `create-app` template (where the plugin is inserted for you), I think it would be useful to call out the dependency right in the logging docs. 

We also use the grails-dependencies POM in our apps to bundle up the "core" deps - perhaps the logging plugin should be added to that as well? 

Of course, let me know if I am misunderstanding anything here!

**Comment by sdelamo** [comment]
We have created a github repository with comparisions between different grails versions to ease upgrade. 

For example, if you are upgrading from 3.2.11 to 3.3.1 you can see the changes:

https://github.com/grails-profiles-versions/web-versions/compare/3.2.11...3.3.1

**Comment by jamesfredley** [comment]
Closing due to age and changes over time in logging.
