### ISSUE TITLE
3.3.1 release missing built docs

### ISSUE THREAD

**Issue by Kapeli** [grails/grails-doc#611]
The 3.1.1 release is missing the built docs zip: https://github.com/grails/grails-doc/releases/tag/v3.3.1

**Comment by graemerocher** [comment]
Thanks for the catch, seems our build failed due to the latest changes in Travis https://travis-ci.org/grails/grails-doc/builds/278615919

**Comment by sdelamo** [comment]
I've checkout #1b12e792, built the build docs zip manually and uploaded the zip to the github release.
