### ISSUE TITLE
Add note about logging changes in 3.3.x Whats new

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-doc#635]
```
James Kleeh:
@erichelgeson Starting in 3.3, the `grails.app.X` logging stuff was removed
It’s just based on the package now
```

Just capturing slack conversation.
I would add it myself but don't know the what or why's to explain the change.

**Comment by sdelamo** [comment]
We already have it documented: 

http://docs.grails.org/latest/guide/conf.html#loggerName

**Comment by erichelgeson** [comment]
As a user updating from 3.2 to 3.3 it would be nice to get a heads up in the Whats New vs. looking through the docs to find changes - I'll add this link into the notable changes section.
