### ISSUE TITLE
Can't publish new docs

### ISSUE THREAD

**Issue by ilopmar** [grails/grails-doc#668]
It seems something has change in the credentials but we can't publish new documentation versions:

![image](https://user-images.githubusercontent.com/559192/40904363-d14a8dc0-67da-11e8-8053-d3251b52c078.png)

https://travis-ci.org/grails/grails-doc/builds/387656202

**Comment by sdelamo** [comment]
Closed by https://github.com/grails/grails-doc/commit/a93705bb6489ddceee0d4a0d0767b26a45518151
