### ISSUE TITLE
EPUB or AsciiDoc output

### ISSUE THREAD

**Issue by CarminePalombo** [grails/grails-doc#679]
Would be great, if possible, to collate all the AsciiDoctor documents together according to toc.yml, in order to generate an EPUB document.
An EPUB document would be nicer than the HTML and more useful than the PDF.
Thanks anyway for this outstanding project!

**Comment by niravassar** [comment]
thanks for the comment. This is more an asciidoc request i think, as that is the tool that generates html and pdf from the input files. 

In the meantime, you could easily take the single.html or single.pdf and convert it to an epub for your own needs. Here is a good article, and i think there are some free online resources as well.

https://www.lifewire.com/best-epub-converters-4582098
