### ISSUE TITLE
Misleading Plugin Upgrade Docs

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-doc#682]
The docs at https://docs.grails.org/3.2.x/guide/upgrading.html#upgradingPlugins suggest that the while upgrading a plugin from Grails 2 to Grails 3, the plugin descriptor should be copied to the new directory structure:

```
cp -rf ../quartz-2.x/QuartzGrailsPlugin.groovy src/main/groovy/grails/plugins/quartz
```

Someone contacted me today to point out that confused them because the descriptor should be moved, not copied, which of course is correct.

The relevant doc source is at https://github.com/grails/grails-doc/blob/f1395971e51f3f614d3b175225c4ffbfbcca34e8/src/en/guide/upgrading/upgrading2x/upgradingPlugins.adoc.

**Comment by sdelamo** [comment]
@jeffbrown The documentation talks about copying resources into the Grails 3 structure (a different folder) to leave the original plugin as it is. Don't think the docs are incorrect.

**Comment by niravassar** [comment]
The documentation first demonstrates that you need to create a new project for a plugin which is grails 3. Then copy resources and sources from old grails 2 plugin project to the new grails 3 plugin project. Therefore the docs are correct.
