### ISSUE TITLE
Latest Grails docs points Grails 3.x and not Grails 4.x

### ISSUE THREAD

**Issue by andersaaberg** [grails/grails-doc#737]
https://docs.grails.org/latest/guide/single.html shows the docs for Grails version "3.3.11" and not Grails version "4.0.1"

**Comment by erichelgeson** [comment]
https://github.com/grails/grails-doc/commit/c7c6fca9b61f6b4669c88495857d71879fd7d718 & re-running 4.0.1 tag job https://travis-ci.org/grails/grails-doc/builds/597786995

Thanks for reporting, will close once job is complete (taking forever to start)

**Comment by erichelgeson** [comment]
Done, Github's CDN takes a while to populate.
