### ISSUE TITLE
Conflicting documented defaults for flushMode

### ISSUE THREAD

**Issue by jchharris** [grails/grails-doc#760]
The Grails documentation states conflicting values for the default flush mode.  It is unclear whether the default is AUTO or COMMIT.  Nor is it it clear that there are apparently two separate settings for flush mode that don't agree with each other.

The Grails upgrade guide states that the hibernate flush mode is now COMMIT by default:

https://grails.github.io/grails-upgrade/latest/guide/index.html

"Flush Mode now COMMIT by Default
The default flush mode has been change to COMMIT due to the impact the previous flush mode AUTO has on read performance. You can switch back to AUTO use the hibernate.flush.mode setting in application.yml"

The GORM Guide states that the flush mode is AUTO by default:

https://gorm.grails.org/latest/hibernate/manual/index.html#_configuration_reference

name | description | default value
-- | -- | --
grails.gorm.flushMode | The flush mode to use | AUTO

**Comment by matrei** [comment]
Fixed by grails/gorm-hibernate5#644
