### ISSUE TITLE
Inconsistency in the definition of the controller scope

### ISSUE THREAD

**Issue by htmfilho** [grails/grails-doc#761]
The version 3.1.1 mentions that the default scope of a controller is "prototype" (https://docs.grails.org/3.1.1/ref/Controllers/scope.html). Version 4.0.3 mentions that the default scope is now "singleton" (https://docs.grails.org/4.0.3/ref/Controllers/scope.html). But when we go to the user guide (https://docs.grails.org/4.0.3/guide/theWebLayer.html#controllersAndScopes) we get "prototype" instead. I can confirm that the same issue happens in the latest version as well. Which documentation needs to be fixed?

**Comment by jamesfredley** [comment]
This was resolved on 6.1.x and 6.2.x.
