### ISSUE TITLE
Update JDK requirements for Grails 4.0.x

### ISSUE THREAD

**Issue by 0branch** [grails/grails-doc#772]
Given the dependency on Spring Boot 2.1.3, I believe that the upper bound JDK is v11—something not obvious from the [requirements](https://docs.grails.org/4.0.5/guide/gettingStarted.html#requirements) documentation which suggests that any version ≥1.8 will work:

> Before installing Grails 4.0.5 you will need as a minimum a Java Development Kit (JDK) installed version 1.8 or above.

**Comment by jamesfredley** [comment]
Resolved by:  https://github.com/grails/grails-doc/pull/828
