### ISSUE TITLE
Broken Link In Docs

### ISSUE THREAD

**Issue by osscontributor** [grails/grails-doc#773]
The docs at https://docs.grails.org/4.0.5/guide/gettingStarted.html#deployingAnApplication have an anchor tag with the text "list of known deployment issues` that points to https://grails.org/wiki/version/Deployment/92 which is a broken link.  The source for that page is at https://github.com/grails/grails-doc/blob/dbb11ad4039ca606e37e0d498fd56db7b5684e8c/src/en/guide/gettingStarted/supportedJavaEEContainers.adoc.

**Comment by matrei** [comment]
Fixed by #845
