### ISSUE TITLE
From 5.1.2 Logback.groovy is not supported

### ISSUE THREAD

**Issue by davymitchell** [grails/grails-doc#823]
From 5.1.2, Logback.groovy is not supported due to logback removing logging support.

Docs need updated to cover this.

It would be useful to have a resource for migrationing from logback.groovy to one of the supported formats.

https://docs.grails.org/5.1.2/guide/single.html#logging

**Comment by jamesfredley** [comment]
https://docs.grails.org/6.2.1/guide/single.html#logging covers logback.groovy retirement

https://github.com/grails/grails-doc/issues/907 will document logback-spring.xml
