### ISSUE TITLE
Question: Does Groovy 3.0.11 really require JDK 11

### ISSUE THREAD

**Issue by matrei** [grails/grails-doc#859]
According to https://github.com/grails/grails-doc/blob/4d6aed76ff3dbad339d06137d4a4bbbb69edbaab/src/en/guide/introduction/whatsNew.adoc#L10C1-L10C1 Groovy 3.0.11 requires JDK 11.

Is this statement correct?

**Comment by puneetbehl** [comment]
Thank you for pointing out. I believe that is wrong. I think the intention is that Grails 6 requires Java 11 at minimum. Please feel free to send a PR to rephrase it.

**Comment by puneetbehl** [comment]
You may be interested to checkout https://docs.grails.org/snapshot/guide/upgrading.html#upgrading50x
