### ISSUE TITLE
Grails 6 documentation does not include guidance on migrating from Grails 5

### ISSUE THREAD

**Issue by Robert-Adelard** [grails/grails-doc#875]
The current version of the Grails documentation, https://docs.grails.org/latest/, does not include guidance on migrating from Grails 5 to Grails 6.

There appears to be a relevant section on GitHub, but it has not been integrated into the latest release:

https://github.com/grails/grails-doc/blob/6.0.x/src/en/guide/upgrading/upgrading50x.adoc

**Comment by puneetbehl** [comment]
Thank you for pointing it out.

**Comment by puneetbehl** [comment]
It is already fixed and will be resolved with Grails 6.1.0. You can also check out the snapshot docs at https://docs.grails.org/snapshot/

**Comment by Robert-Adelard** [comment]
Thank you - however, I am surprised that Grails 6.0.0 was released without any upgrade documentation, since the section on upgrading from the previous version of Grails is essential reading for anyone wanting to migrate an existing application.

If the issue has been fixed, I think it would be worth updating https://docs.grails.org/latest which currently points to the 6.0.0 documentation - it's not obvious that there's also a snapshot version.

I realise that https://docs.grails.org/latest will be updated automatically when 6.1.0 is released but in the meantime the 6.0.0 documentation is incomplete, despite Grails 6.0.0 having been released three months ago...
